version: "3.8"
services:
  mongodb:
    image : mongo:latest
    container_name: price-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_USER=${MONGODB_USER}
      - MONGO_INITDB_PWD=${MONGODB_PASS}
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb-data:/data/db
      - ./init.d/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - 27017:27017
    #    network_mode: host
    #restart: unless-stopped
  redis:
    image: redis:latest
    container_name: price-redis
    ports:
      - ${REDIS_PORT}:6379
    #    network_mode: host
    restart: unless-stopped
volumes:
  mongodb-data: